name: Keep Bot Alive
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Bot Health Endpoint
        run: |
          curl -f https://your-render-app.onrender.com/health
        env:
          # Add your Render app URL in repository secrets if needed
          BOT_URL: ${{ secrets.BOT_URL }}
      
      - name: Log Response
        run: |
          echo "Bot pinged successfully at $(date)"